### ISSUE TITLE
Investigate automation of publishing new npm versions

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-api-headers#13]
Seems like after a PR to update is reviewed/landed we could automate publishing a new version.

**Comment by KevinEady** [comment]
I can take a look at this. 

I am wondering about what we should do with the versioning of our package? Should it match the Node.js version the headers are based on? For example, after merging #40 , we would publish this package as version `22.1.0`? I think we had this discussion before but not sure the outcome (if there was one)? 

If we don't go with that, what would our versioning scheme be -- just update the minor version every time? 

What are your thoughts @NickNaso ?

**Comment by NickNaso** [comment]
Hi @KevinEady you are right and we decided to follow the rules reported in the section `Version` of the docs https://github.com/nodejs/node-api-headers?tab=readme-ov-file#versions.
I think that is the simpler thing that we can do.

**Comment by NickNaso** [comment]
Hi @KevinEady,
I agree with you maybe we should trigger the `publish-release` workflow only when a branch `release/v<version>` is merged or manually.

**Comment by legendecas** [comment]
Automation verified at https://github.com/nodejs/node-api-headers/pull/45.
