### ISSUE TITLE
Sync headers needed

### ISSUE THREAD

**Issue by Pospelove** [nodejs/node-api-headers#20]
Hey! Could you please trigger headers sync? This would trigger .def files generation which is required for https://github.com/microsoft/vcpkg/pull/29743 @NickNaso

**Comment by KevinEady** [comment]
Hi @legendecas , this is because `git diff` does not report changes for untracked files. #21 should resolve this.

**Comment by NickNaso** [comment]
Hi everybody,
after the merge of https://github.com/nodejs/node-api-headers/pull/21 I will make the new release v0.0.5.

**Comment by legendecas** [comment]
Done in https://github.com/nodejs/node-api-headers/pull/22

**Comment by Pospelove** [comment]
Thanks a lot!
