### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by NickNaso** [nodejs/node-api-headers#31]
We should create a new release to bring the last update from the Node.js core repo. Node-API v9 has been shipped but for this repo and accordingly with https://github.com/nodejs/node-api-headers#versions the next versione will be `v1.1.0`. 
Is it right @nodejs/node-api ?

**Comment by mhdawson** [comment]
@NickNaso agree.

**Comment by NickNaso** [comment]
I'm glosing the issue because the version v1.1.0 has been released.
