### ISSUE TITLE
Wrong symbols in v6.node_api_symbols

### ISSUE THREAD

**Issue by guentner** [nodejs/node-api-headers#5]
`v6.node_api_symbols` should probably extend `v5.node_api_symbols` instead of `v5.js_native_api_symbols`.

https://github.com/nodejs/node-api-headers/blob/d68505e4055ecb630e14c26c32e5c2c65e179bba/symbols.js#L189

**Comment by NickNaso** [comment]
@guentner you are right I just made a PR to solve the problem. Thanks for reporting.

**Comment by legendecas** [comment]
Fixed in #6
